# Mail Config
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL:email}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
