# RabbitMQ Config
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rabbitmq}
    password: ${RABBITMQ_PASSWORD:rabbitmq}

rabbitmq:
  exchange: mail-exchange

  account:
    queue: mail.account.queue
    routing: mail.account.routing

  verify:
    queue: mail.verify.queue
    routing: mail.verify.routing